"default":
- - 'No Boundaries Available'
  - '0/none'
"http://demo.geoiq.com":
- - 'State - Full Name'
  - '2092/state'
- - 'State - Abbreviation'
  - '2092/st'
- - 'State - FIPS'
  - '2092/fips'
"http://api-sandbox.geoiq.com":
- - 'State - Full Name'
  - '522/state'
- - 'State - Abbreviation'
  - '522/st'
- - 'State - FIPS'
  - '522/fips'
- - 'Country - Full Name'
  - '527/NAME'
- - 'Country - 3 Letter GMI Code'
  - '527/GMI_CNTRY'
- - 'Country - 2 Letter ISO Code'
  - '527/ISO_2_CODE'
- - 'Country - 3 Letter ISO Code'
  - '527/ISO_3_CODE'
- - 'County - County and State (no spaces)'
  - '645/countysta'
- - 'County - State and County (no spaces)'
  - '645/statecount'
- - 'County - Name Only'
  - '645/b'
- - 'County - FIPS'
  - '645/f'
- - 'Congressional District'
  - '648/cd_1'
- - 'Zip - Numeric'
  - '645/ZIP'
"http://geoiq.issuemapperqa.geoiq.com":
- - 'State - Full Name (e.g. Arkansas)'
  - '14/state'
- - 'State - Abbreviation (e.g. AK)'
  - '14/st'
- - 'State - FIPS'
  - '14/fips'
- - 'Country - Full Name (e.g. France)'
  - '16/NAME'
- - 'Country - 3 Letter GMI Code'
  - '16/GMI_CNTRY'
- - 'Country - 2 Letter ISO Code (e.g. FR)'
  - '16/ISO_2_CODE'
- - 'Country - 3 Letter ISO Code (e.g. FRA)'
  - '16/ISO_3_CODE'
- - 'County - County and State (no spaces) (e.g. Springfield,MO)'
  - '17/countysta'
- - 'County - State and County (no spaces)'
  - '17/statecount'
- - 'County - Name Only (e.g. Arlington)'
  - '17/b'
- - 'County - FIPS'
  - '17/f'
- - 'Congressional District'
  - '21/cd_1'
- - 'Zip - Numeric (e.g. 22201)'
  - '17/ZIP'
"http://geoiq.issuemapper.geoiq.com":
- - 'State - Full Name'
  - '19/state'
- - 'State - Abbreviation'
  - '19/st'
- - 'State - FIPS'
  - '19/fips'
- - 'Country - Full Name'
  - '25/NAME'
- - 'Country - 3 Letter GMI Code'
  - '25/GMI_CNTRY'
- - 'Country - 2 Letter ISO Code'
  - '25/ISO_2_CODE'
- - 'Country - 3 Letter ISO Code'
  - '25/ISO_3_CODE'
- - 'County - County and State (no spaces)'
  - '15/countysta'
- - 'County - State and County (no spaces)'
  - '15/statecount'
- - 'County - Name Only'
  - '15/b'
- - 'County - FIPS'
  - '15/f'
- - 'Congressional District'
  - '14/cd_1'
- - 'FCC Basic Trading Areas - Area ID'
  - '13/Bta'
- - 'FCC Basic Trading Areas - Name'
  - '13/Name'
- - 'FCC Economic Area Groupings - Area ID'
  - '12/Eag'
- - 'FCC Economic Area Groupings - Name'
  - '12/Name'
- - 'FCC Cellular Market Areas - Area ID'
  - '11/Cma'
- - 'FCC Cellular Market Areas - Name'
  - '11/Name'
- - 'FCC Major Trading Areas - Area ID'
  - '10/Mta'
- - 'FCC Major Trading Areas - Name'
  - '10/Name'
- - 'FCC Major Economic Areas - Area ID'
  - '9/Mea'
- - 'FCC Major Economic Areas - Name'
  - '9/Name'
- - 'FCC Regional PCS Areas - Area ID'
  - '8/Rpc'
- - 'FCC Regional PCS Areas - Name'
  - '8/Name'
- - 'FCC Public Safety Planning Regions - Area ID'
  - '7/Psr'
- - 'FCC Public Safety Planning Regions - Name'
  - '7/Name'